### ISSUE TITLE
Google API setup

### ISSUE THREAD

**Issue by parkeragee** [jakubgarfield/expenses#2]
Can you add the "getting started" steps to create the required Google API/Client ID with the correct scopes?

**Comment by jakubgarfield** [comment]
Good point – just to get you started quickly you need OAuth and read/write access to Google Sheets and read access to Google Drive

https://developers.google.com/sheets/api/guides/authorizing

**Comment by leocabeza** [comment]
It's good to note that you have to join this group: [https://groups.google.com/forum/#!forum/risky-access-by-unreviewed-apps)](https://groups.google.com/forum/#!forum/risky-access-by-unreviewed-apps) in case you are replacing the clientId for your own clientId and project.
