### ISSUE TITLE
Not working after signin

### ISSUE THREAD

**Issue by dashokkumar93** [jakubgarfield/expenses#6]
http://imgur.com/a/vpaBA
Please look at this link there has been an error after the singin

**Comment by jakubgarfield** [comment]
Someone modified the spreadsheet that backs up the data again.

<img width="967" alt="screen shot 2017-07-24 at 8 09 49 am" src="https://user-images.githubusercontent.com/194724/28510303-e92d148e-7047-11e7-9299-12473040f6cb.png">

**Comment by tvardy** [comment]
So what's the fix though?

**Comment by jakubgarfield** [comment]
Oh sorry – I fixed the spreadsheet (the format needs to be as https://docs.google.com/spreadsheets/d/1Lz1_gHIgCKPKhJpFerq9PoNy-TIst7eLZ5plQi5Prv0/edit). It should be working now.
